# vib

name: slow-scroll # Replace this name with your image name
id: slow-scroll-zachdachampion # Replace this ID with your image ID
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main # Optionally, Replace this image URL with a different one i.e. nvidia:main, etc
  singlelayer: false
  labels:
    maintainer: ZachDaChampion # Optionally, Replace this with your name
  args:
    DEBIAN_FRONTEND: noninteractive # Set the image environment as non-interactive
  
  # Commands to run first before building the modules
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt-get update

  # Put your custom actions behind this comment

  - name: install-dependencies
    type: apt
    source:
      packages:
        - ninja-build
        - libinput-dev

  - name: build-libinput-config
    type: meson
    source:
      url: "https://gitlab.com/warningnonpotablewater/libinput-config/-/archive/default/libinput-config-default.tar.gz"
      type: tar

  - name: set-scroll-speed
    type: shell
    commands:
    - touch /etc/libinput.conf
    - echo 'scroll-factor=0.33' > /etc/libinput.conf

  - name: cleanup-ninja-libinput
    type: shell
    commands:
    - apt-get remove ninja-build libinput-dev -y

  # Put your custom actions before this comment

  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml

  - name: cleanup
    type: shell
    commands:
    - apt-get autoremove -y
    - apt-get clean
    - lpkg --lock

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard 
          - rm -f ./minisign.pub ./minisign.key 
          - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
